deployment:
  tasks:
    - C:\xamppf\php\php.exe C:\xamppf\htdocs\SIS_TECNONAUTAS\artisan migrate --force
    - C:\xamppf\php\php.exe C:\xamppf\htdocs\SIS_TECNONAUTAS\artisan config:cache
    - C:\xamppf\php\php.exe C:\xamppf\htdocs\SIS_TECNONAUTAS\artisan route:cache
    - C:\xamppf\php\php.exe C:\xamppf\htdocs\SIS_TECNONAUTAS\artisan view:cache
